package methods;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class Hash
{
    public static byte[] getSha(String password) throws NoSuchAlgorithmException
    {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        //message digest() getting called to calculate message of input
        //returns byte array of the password
        return md.digest(password.getBytes(StandardCharsets.UTF_8));
    }
    public static String shaHash(byte[] data)
    {
        //byte Array into signum representation conversion
        BigInteger bi = new BigInteger(1, data);
        //message digest into gex value conversion
        StringBuilder hash = new StringBuilder(bi.toString(16));
        while (hash.length() < 64)
        {
            hash.insert(0,'0');
        }
        return hash.toString();
    }

    public static void main(String args[])
    {
        try
        {
            System.out.println("HashCode Generated by SHA-256 for:");

            String s1 = "GeeksForGeeks";
            System.out.println("\n" + s1 + " : " + shaHash(getSha(s1)));

            String s2 = "hello world";
            System.out.println("\n" + s2 + " : " + shaHash(getSha(s2)));

            String s3 = "K1t4fo0V";
            System.out.println("\n" + s3 + " : " + shaHash(getSha(s3)));
        }
        // For specifying wrong message digest algorithms
        catch (NoSuchAlgorithmException e) {
            System.out.println("Exception thrown for incorrect algorithm: " + e);
        }
    }
}
